age/urls.py
from django.contrib import admin
from django.urls import path
from .views import review, simple_webservice

#app_name = 'age'

urlpatterns = [
    path('admin/', admin.site.urls),
    path('review/', review, name='review'),
    path('webservice/', simple_webservice)
]

amiya/urls.py
from django.urls import path
from . import views

app_name = 'amiya'

urlpatterns = [
    path('recommendMovie/', views.recommendMovie, name='recommendMovie'),
    path('webservice/', views.simple_webservice),
]

billa/urls.py
from django.urls import path
from . import views

app_name = 'billa'

urlpatterns = [
    path('searchMovie/', views.searchMovie, name='searchMovie'),
    path('webservices/', views.simple_webservices),
]

fadhil/urls.py
from django.contrib import admin
from django.urls import path
from .views import library, simple_webservice

app_name = 'fadhil'

urlpatterns = [
    path('admin/', admin.site.urls),
    path('library/', library, name =  'library'),
    path('webservice/', simple_webservice),
]

login/urls.py
from django.contrib import admin
from django.urls import path
from .views import index, register, logout

urlpatterns = [
    path('', index),
    path('signup/',register, name='signup'),
    path('', logout, name='logout'),
]

tk2/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('login.urls')),
    path('',include('age.urls')),
    path('', include('billa.urls')),
    path('',include('amiya.urls')),
    path('',include('fadhil.urls', namespace = 'fadhil')),
    path('account/',include('django.contrib.auth.urls')),
]

age/models.py
from django.db import models

class Movies(models.Model):
    movies = models.CharField(max_length=100)

amiya/models.py
from django.db import models

# Create your models here.
class Movies(models.Model):
    title = models.CharField(max_length=100)

billa/models.py
from django.db import models


# Create your models here.
class Movies(models.Model):
    title = models.CharField(max_length=100)

fadhil/models.py
from django.db import models

class Movies(models.Model):
    title=models.CharField(max_length=100)
# Create your models here.

login/models.py
from django.db import models

# Create your models here.

age/forms.py
from django import forms
from .models import Review

class ReviewForm(forms.ModelForm):
    class Meta:
        model = Review
        fields = ['review_title', 'review']

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.user = user
        
        for field in self.Meta.fields:
            self.fields[field].widget.attrs.update({
                'class' : 'form-control'
            })

amiya/forms.py
from django import forms
from .models import Movies

# class searchbox (forms.Form):
#     search_query = forms.CharField(min_length=1)

class MoviesForms(forms.ModelForm):
    class Meta:
        model = Movies
        fields = ['title']
        widgets = {
            'title' : forms.Textarea(attrs={'cols':10, 'rows': 5, "class":"form-control"}),

        }

billa/forms.py
from django import forms

age/views.py
from django.shortcuts import render
from .models import Movies
from django.http import JsonResponse

def review(request):
    movies = None

    if 'search' in request.GET.keys() :
        keyword = request.GET['search'] 
        movies = Movies.objects.filter(title = keyword)

    return render(request, 'age.html',{ 'Movies' : movies})


def simple_webservice(request):
    data_dikirim = {'data_1': 'abc', 'data_2': 'def', 'data_3': 'ghi'}
    return JsonResponse(data=data_dikirim)

amiya/views.py
from django.shortcuts import render
from .models import Movies
from django.http import JsonResponse

# Create your views here.

def recommendMovie(request):
    movies = None

    if 'search' in request.GET.keys() :
        keyword = request.GET['search'] 
        movies = Movies.objects.filter(title = keyword)

    return render(request, 'recommendMovie.html',{ 'Movies' : movies})


def simple_webservice(request):
    data_dikirim = {'data_1': 'abc', 'data_2': 'def', 'data_3': 'ghi'}
    return JsonResponse(data=data_dikirim)

billa/views.py
from django.shortcuts import render
from .models import Movies
from django.http import JsonResponse

# Create your views here.

def searchMovie(request):
    movies = None

    if 'search' in request.GET.keys() :
        keyword = request.GET['search']
        movies = Movies.objects.filter(title = keyword)

    return render(request, 'searchMovie.html',{ 'Movies' : movies})

def simple_webservices(request):
    data_dikirim ={'data_1' : 'abc','data_2':'def','data_3':'ghi' }
    return JsonResponse(data=data_dikirim)

fadhil/views.py
from django.shortcuts import render
from .models import Movies
from django.http import JsonResponse



# def index(request):
#     response = {}
#     return render(request, 'landing.html',response)

# def library(request):
#     response = {}
#     return render(request,'library.html',response)

def library(request):
    movies = None

    if 'search' in request.GET.keys() :
        keyword = request.GET['search'] 
        movies = Movies.objects.filter(title = keyword)

    return render(request, 'library.html',{ 'Movies' : movies})


def simple_webservice(request):
    data_dikirim = {'data_1': 'abc', 'data_2': 'def', 'data_3': 'ghi'}
    return JsonResponse(data=data_dikirim)

login/views.py
from django.shortcuts import render,redirect
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import authenticate, login, logout


def index(request):
    response = {}
    return render(request,'landing.html',response)

def register(request):
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data['username']
            password = form.cleaned_data['password1']
            user = authenticate(username = username, password=password)
            login(request, user)
            return redirect('/')
    else:
        form = UserCreationForm()
    context = {'form' : form}
    return render(request, 'registration/signup.html', context)

def logout(request):
    logout(request)
    return redirect('/')

age/templates/age.html
<!DOCTYPE html>
{% load static %}
<!DOCTYPE html>
<html lang="en" dir="ltr">

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width =device-width">
  <link rel="stylesheet" href="{% static 'css/style.css' %}">
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">.
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
  <link href="https://fonts.googleapis.com/css?family=Libre+Caslon+Text&display=swap" rel="stylesheet">       

  <title> Now Playing </title>
</head>

<body>
  <nav class="navbar navbar-expand-lg navbar-light justify-content-center fixed-top hehe">
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarMenu" aria-controls="navbarTogglerDemo02" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarMenu">
        <ul class="navbar-nav" style=" margin-right:-1vw;">
            <li class="nav-item" >
                    <a style="color:#FF786A;  font-family: 'Libre Caslon Text',serif;" class="nav-link" >MOVIE GOERS</a>
            </li>
            <li class="nav-item">
                <a style="color:black; margin-left: 55vw;  font-family: 'Libre Caslon Text',serif;" class="nav-link" href="{% url 'billa:searchMovie' %}" ><b>Search</b></a>
            </li>
            <li class="nav-item">
                <a style="color:black;  font-family: 'Libre Caslon Text',serif;" class="nav-link" href="{% url 'fadhil:library' %}" ><b>#NP</b></a>
            </li>
            <li class="nav-item">
                <a  style="color:black;  font-family: 'Libre Caslon Text',serif;" class="nav-link" href="{% url 'amiya:recommendMovie' %}"><b>Recommendation</b></a>
            </li>
            <li class="nav-item">
                    <a  style="color:#FF786A;  font-family: 'Libre Caslon Text',serif;" class="nav-link" href="{% url 'review' %}"><b>Upcoming</b></a>
                </li>
            {% if user.is_authenticated %}
            <li class="nav-item">
                <a  style="color:black;  font-family: 'Libre Caslon Text',serif; background-color: #FF786A;" class="nav-link" href="{% url 'logout' %}"><b>Logout</b></a>
            </li>
            {% endif %}
        </ul>
    </div>
</nav>

  <div class="background-col" style= "color:black;" >
    <div class="container">
      <header class="text-center mt-5">
          <h1 class="d-flex justify-content-center" style=" font-family: 'Libre Caslon Text',serif; font-size: 4vw;">Hello, {{ user.username}}</h1>
           <h3 class="font-weight-light judul2">Upcoming Movies</h3>
      </header>
    </div>

    <div class="container">      
  <!-- Modal -->
  <div class="modal fade" id="exampleModalCenter" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
      <div class="modal-dialog modal-dialog-centered" role="document">
        <div class="modal-content">
          <div class="modal-header">
            <h5 class="modal-title" id="exampleModalLongTitle">Overview</h5>
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
              <span aria-hidden="true">&times;</span>
            </button>
          </div>
          <div class="modal-body">
          <div class="tengah">
            <img class="fotoP justify-content-center"></img>
          </div>
            <div class="judulP"></div>
            <paragraph class="paragraphP"> </paragraph>
            <button class="buttonP"> Add to Favorite </button>
            <button class="buttonP2"> Details </button>
            <div class="tengah">
                  <input class="inputP">  </input>
            </div>
  
  
          </div>
          <div class="modal-footer">
  
  
          </div>
        </div>
      </div>
    </div>
    </div>
              
    <div class="container align-middle ">
      <div class="row text-center">  
        <div class="form-group shadow-textarea">
          <button id="NPbutton"class="align-middle"> Whats next? </button>
        </div>
      </div>
    </div>
    <div class="container">
      <div class="row">
        <div id="results" class="results" style= " margin-left: 40%; margin-right: 40%;">

              </div>
        </div>
        
      </div>
    </div>
  </div>
          
<script src= "https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"> </script>
<script src = "{% static 'js/jquery.js' %}"></script>
<script src = "{% static 'js/jsAge.js' %}"></script>
<script src= "https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"> </script>
<script src= "https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"> </script>
<script src= "https://use.fontawesome.com/releases/v5.0.8/js/all.js"> </script>


</body>


</html>

amiya/templates/recommendMovie.html
<!DOCTYPE html>
{% load static %}
<!DOCTYPE html>
<html lang="en" dir="ltr">

<head>
        <meta charset="utf-8">
        <meta name="viewport" content="width =device-width">
        <link rel="stylesheet" href="{% static 'css/style.css' %}">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">.
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js">
        </script>
        <link href="https://fonts.googleapis.com/css?family=Libre+Caslon+Text&display=swap" rel="stylesheet">       
        <title> Recommend Movie </title>
</head>

<body>

    <nav class="navbar navbar-expand-lg navbar-light justify-content-center fixed-top hehe">
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarMenu" aria-controls="navbarTogglerDemo02" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarMenu">
                <ul class="navbar-nav" style=" margin-right:-1vw;">
                    <li class="nav-item" >
                            <a style="color:#FF786A;  font-family: 'Libre Caslon Text',serif;" class="nav-link" >MOVIE GOERS</a>
                    </li>
                    <li class="nav-item">
                        <a style="color:black; margin-left: 55vw;  font-family: 'Libre Caslon Text',serif;" class="nav-link" href="{% url 'billa:searchMovie' %}" ><b>Search</b></a>
                    </li>
                    <li class="nav-item">
                        <a style="color:black;  font-family: 'Libre Caslon Text',serif;" class="nav-link" href="{% url 'fadhil:library' %}" ><b>#NP</b></a>
                    </li>
                    <li class="nav-item">
                        <a  style="color:#FF786A;  font-family: 'Libre Caslon Text',serif;" class="nav-link" href="{% url 'amiya:recommendMovie' %}"><b>Recommendation</b></a>
                    </li>
                    <li class="nav-item">
                            <a  style="color:black;  font-family: 'Libre Caslon Text',serif;" class="nav-link" href="{% url 'review' %}"><b>Review</b></a>
                        </li>
                    {% if user.is_authenticated %}
                    <li class="nav-item">
                        <a  style="color:black;  font-family: 'Libre Caslon Text',serif; background-color: #FF786A;" href="{% url 'logout' %}" class="nav-link"><b>Logout</b></a>
                    </li>
                    {% endif %}
                </ul>
            </div>
        </nav>

    {% if user.is_authenticated %}
        <div class="background-col" style= "background: white; color:black;" >

                <div class="container">
                <header class="text-center mt-5">
                    <h1 class="d-flex justify-content-center" style=" font-family: 'Libre Caslon Text',serif; font-size: 4vw;">Hello, {{ user.username}}</h1>
                     <h3 class="font-weight-light judul2">Here's a recommendation for you.</h3>
              
                </header>
                <!-- Button trigger modal -->
  <!-- Modal -->
  <div class="modal fade" id="exampleModalCenter" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="exampleModalLongTitle">Overview</h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="modal-body">
        <div class="tengah">
          <img class="fotoP justify-content-center"></img>
        </div>
          <div class="judulP"></div>
          <paragraph class="paragraphP"> </paragraph>
          <button class="buttonP"> Add to Favorite </button>
          <button class="buttonP2"> Details </button>
          <div class="tengah">
                <input class="inputP">  </input>
          </div>


        </div>
        <div class="modal-footer">


        </div>
      </div>
    </div>
  </div>
                </div>
              
                <div class="container text-center ">
              
                    <!-- <h5 class="description">Search your book here!</h5> -->
                    <div class="row text-center d-flex justify-content-center">
              
              
              
                      <div class="col-md-4 center-block justify-content-center">

                          <button class="RecButton" id="UPbutton"> Upcoming </button>
                          <button class="RecButton" id="TRbutton"> Top Rated </button>
                          <button class="RecButton" id="Pbutton"> Popular </button>

                      </div>
                    </div>
                    <div class="row">
                      <div id="results" class="  results " style= " margin-left: 40%; margin-right: 40%;">
                    </div>
                    </div>
                </div>
              </div>
{% else %}
<div class="container">
    <div class="row">
        <div class="col-sm-6 text">
        <div class="col-md-12 col-sm-12">
            <h1 style="color: black; font-family: 'Libre Caslon Text',serif; font-size: 7vw; ;"> <b>Please <br> sign in<br> first</b></h1>
        </div>
        <div class="col-md-62 col-sm-62"  style="color: grey;">
                <a id="login" href="{% url 'login' %}" class="btn btn-outline-dark text-dark">Sign In</a>
        </div>
        </div>

    </div>
</div>
{% endif %}

<script src= "https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"> </script>

<script src = "{% static 'js/jquery.js' %}"></script>
<script src = "{% static 'js/jsamiya.js' %}"></script>

<script src= "https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"> </script>
<script src= "https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"> </script>
<script src= "https://use.fontawesome.com/releases/v5.0.8/js/all.js"> </script>

        

</body>


</html>

billa/templates/searchMovie.html
<!DOCTYPE html>
{% load static %}
<!DOCTYPE html>
<html lang="en" dir="ltr">

    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width =device-width">
        <link rel="stylesheet" href="{% static 'css/searchMovie.css' %}">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">.
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
        <link href="https://fonts.googleapis.com/css?family=Libre+Caslon+Text&display=swap" rel="stylesheet">       

        <title> Search Movie </title>
</head>

<body>

    <nav class="navbar navbar-expand-lg navbar-light justify-content-center fixed-top hehe">
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarMenu" aria-controls="navbarTogglerDemo02" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarMenu">
                <ul class="navbar-nav" style=" margin-right:-1vw;">
                    <li class="nav-item" >
                            <a style="color:#FF786A;  font-family: 'Libre Caslon Text',serif;" class="nav-link" >MOVIE GOERS</a>
                    </li>
                    <li class="nav-item">
                        <a style="color: #FF786A; margin-left: 55vw;  font-family: 'Libre Caslon Text',serif;" class="nav-link" ><b>Search</b></a>
                    </li>
                    <li class="nav-item">
                        <a style="color:black;  font-family: 'Libre Caslon Text',serif;" class="nav-link" href="{% url 'fadhil:library' %}"><b>#NP</b></a>
                    </li>
                    <li class="nav-item">
                        <a  style="color:black;  font-family: 'Libre Caslon Text',serif;" class="nav-link" href="{% url 'amiya:recommendMovie' %}"><b>Recommendation</b></a>
                    </li>
                    <li class="nav-item">
                            <a  style="color:black;  font-family: 'Libre Caslon Text',serif;" class="nav-link" href="{% url 'review' %}"><b>Review</b></a>
                        </li>
                    {% if user.is_authenticated %}
                    <li class="nav-item">
                        <a  style="color:black;  font-family: 'Libre Caslon Text',serif; background-color: #FF786A;" class="nav-link" href="{% url 'logout' %}"><b id="logout">Logout</b></a>                    </li>
                    {% endif %}
                </ul>
            </div>
        </nav>
        
       
    {% if user.is_authenticated %}
    <div class="background-col" style= "background: white; color:black;" >

            <div class="container">
            <header class="text-center mt-5">
                <h1 class="d-flex justify-content-center" style=" font-family: 'Libre Caslon Text',serif; font-size: 4vw;">Hello, {{ user.username}}</h1>
                 <h3 class="font-weight-bold judul2" style="font-family: 'Libre Caslon Text'">Let's Find a Movie!</h3>
          
            </header>

  <!-- Modal -->
  <div class="modal fade" id="exampleModalCenter" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="exampleModalLongTitle">Overview</h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="modal-body">
        <div class="tengah">
          <img class="fotoP justify-content-center"></img>
        </div>
          <div class="judulP"></div>
          <paragraph class="paragraphP"> </paragraph>
          <button class="buttonP"> Add to Favorite </button>
          <button class="buttonP2"> Details </button>
          <div class="tengah">
                <input class="inputP">  </input>
          </div>


        </div>
        <div class="modal-footer">


        </div>
      </div>
    </div>
  </div>
                </div>
              
                <div class="container text-center">
              
                    <!-- <h5 class="description">Search your book here!</h5> -->
                    <br>
                    <div class="row text-center d-flex justify-content-center" style = "background-color:white;">
              
              
              
                      <div class="form-group shadow-textarea  justify-content-center text-center" >
                          <!-- <input id="search" placeholder="Title or Author"> -->
                          <!-- <button id="button" name="button">Search</button> -->
                          <input type="text" id="isi" class="form-light"  style="border-radius:12px; padding: 1vh 10vw; text-align: center;" placeholder="type the title">
                      </div>
                    </div>              
    
              
              
              
              
              
              
                </div>


              

                <div id="results" class="  results " style= " margin-left: 40%; margin-right: 40%;">
              
              
              
                </div>
              
              
              
              
              
              
              </div>


              {% else %}
              <div class="container">
                <div class="row">
                <div class= "col-md-6 d-flex justify-content-center align-items-center" >
                    <div class="text">
                        <div class="col-md-12">
                            <h1 style="color: black; font-family: 'Libre Caslon Text',serif; font-size: 7vw; ;"> <b> Please <br> Sign-In <br> First</b></h1>
                        </div>
                        <div class="col-md-62 col-sm-62"  style="color: grey;">
                                <a id="login" href="{% url 'login' %}" class="btn btn-outline-dark text-dark">Sign In</a>
                        </div>
                    </div>
                </div>
                <div class="col-md-6 d-flex justify-content-center align-items-center " style="margin-left: -10px;">
                    <img src="{% static 'images/logo.png' %}">
                </div>
                </div>
        
                </div>  
        
            </div>
              {% endif %}
<script src= "https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"> </script>

<script src = "{% static 'js/jquery.js' %}"></script>
<script src = "{% static 'js/jsbilla.js' %}"></script>

<script src= "https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"> </script>
<script src= "https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"> </script>
<script src= "https://use.fontawesome.com/releases/v5.0.8/js/all.js"> </script>


</body>


</html>

login/templates/landing.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
        <meta charset="utf-8">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
        <link href="https://fonts.googleapis.com/css?family=Libre+Caslon+Text&display=swap" rel="stylesheet">       
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>
        <script src="https://code.jquery.com/jquery-1.12.4.js"></script>
        <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
        <title> Movie Goers </title>
</head>
<body>
        <nav class="navbar navbar-expand-lg navbar-light justify-content-center fixed-top hehe">
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarMenu" aria-controls="navbarTogglerDemo02" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarMenu">
                    <ul class="navbar-nav" style=" margin-right:1vw;">
                        <li class="nav-item" >
                             <a style="color:#FF786A;  font-family: 'Libre Caslon Text',serif;" class="nav-link"><b>MOVIE GOERS</a>
                        </li>
                
                    </ul>
                </div>
        </nav>
   
   <br><br>
    {% if user.is_authenticated %}
    <div class="container">
        <div class="row">
        <div class= "col-sm-6 d-flex justify-content-center align-items-center">
        <div class="text">
            <div class="col-md-12 ">
                <h1 style="color: black; font-family: 'Libre Caslon Text',serif; font-size: 5vw; ;">Now you are logged in, {{ user.username}}</h1>
            </div>
            <div class="col-md-12 ">
                <a id="cari" href="{% url 'billa:searchMovie' %}" class="btn btn-outline-dark text-dark">Search</a>
            </div>
            <div class="col-md-12 ">
                <a id="cari"  class="btn btn-outline-dark text-dark" href="{% url 'fadhil:library' %}">Now Playing</a>
            </div>
            <div class="col-md-12 ">
                <a id="cari" href="{% url 'amiya:recommendMovie' %}" class="btn btn-outline-dark text-dark">Recommendation</a>

            </div>
            <div class="col-md-12 ">
                <a id="cari" href="{% url 'review' %}" class="btn btn-outline-dark text-dark">Review</a>
            </div>
            <div class="col-md-12 ">
                    <a id="logout" href="{% url 'logout' %}" class="btn btn-outline-dark text-dark">Sign Out</a>
            </div>
        </div>
        </div>
           
        <div class="col-md-6 d-flex justify-content-center align-items-center " style="margin-left: -10px;">
                <img src="{% static 'images/logo.png' %}">
        </div>

        </div>
    </div>
    {% else %}
    <div class="container">
        <div class="row">
        <div class= "col-md-6 d-flex justify-content-center align-items-center" >
            <div class="text">
                <div class="col-md-12">
                    <h1 style="color: black; font-family: 'Libre Caslon Text',serif; font-size: 7vw; ;"> <b> Please <br> Sign-In <br> First</b></h1>
                </div>
                <div class="col-md-62 col-sm-62"  style="color: grey;">
                        <a id="login" href="{% url 'login' %}" class="btn btn-outline-dark text-dark">Sign In</a>
                </div>
            </div>
        </div>
        <div class="col-md-6 d-flex justify-content-center align-items-center " style="margin-left: -10px;">
            <img src="{% static 'images/logo.png' %}">
        </div>
        </div>

        </div>  

    </div>
    {% endif %}

</body>
</html>

login/templates/welcome.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" type = "text/css" href= "{% static 'css/style.css' %}">
    <title>Welcome Page</title>
</head>
<body class= body-bg2>
    <h1 class= "welcome"> HELLO WELCOME, {{ request.session.nama }}. </h1>
    <form action='/logout' method='POST'>
    {% csrf_token %}
    <input class= "logoutbutt" type="submit" name='' value="logout">
    </form>
</body>
</html>